apiVersion: v1
kind: Pod
metadata:
  name: test-kata-cdi-vfio
  namespace: nemo
  annotations:
    cdi.k8s.io/vfio0: "nvidia.com/pgpu=0"
spec:
  restartPolicy: Never
  runtimeClassName: kata-qemu-nvidia-gpu
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
  containers:
  - name: test-cdi-vfio
    image: nvcr.io/nvidia/cuda:11.6.0-base-ubuntu20.04
    command: ["/bin/bash", "-c", "lspci -nn | grep -i nvidia && echo 'GPU found via CDI!'"]
    securityContext:
      privileged: true
