apiVersion: v1
kind: Pod
metadata:
  name: test-tdx-gpu
  namespace: nemo
spec:
  restartPolicy: Never
  runtimeClassName: kata-qemu-nvidia-gpu-tdx
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
  containers:
  - name: test-tdx-gpu
    image: nvcr.io/nvidia/cuda:11.6.0-base-ubuntu20.04
    command: ["/bin/bash", "-c", "echo 'TDX GPU test starting' && sleep 10 && echo 'TDX GPU test completed'"]
    securityContext:
      privileged: true
    resources:
      limits:
        nvidia.com/GH100_H200_SXM_141GB: 1

