apiVersion: v1
kind: Pod
metadata:
  name: test-kata-nvidia-gpu
  namespace: nemo
spec:
  restartPolicy: Never
  runtimeClassName: kata-nvidia-gpu
  nodeSelector:
    nvidia.com/gpu.deploy.kata-manager: "true"
  containers:
  - name: test-kata-nvidia-gpu
    image: nvcr.io/nvidia/cuda:11.6.0-base-ubuntu20.04
    command: ["/bin/bash", "-c", "echo 'Kata NVIDIA GPU test starting' && sleep 10 && echo 'Kata NVIDIA GPU test completed'"]
    securityContext:
      privileged: true
    resources:
      limits:
        nvidia.com/GH100_H200_SXM_141GB: 1

